### ISSUE TITLE
Allow output target specification

### ISSUE THREAD

**Issue by d-rams** [nix7drummer88/pigz-python#30]
Currently this tool will take a file at absolute location `path.parent / path.name` and put it at `cwd / path.name + '.gz'` which is incredibly annoying.  Perhaps this is a bug?

For instance, suppose you're working in a temporary directory.  This tool will write the zipped version outside of the temporary directory and then you need to manually delete it. 

Instead we should allow the user to specify the output location for the .gz file.  If we don't do that, at least we should put it in the same directory as the uncompressed version.

**Comment by nix7drummer88** [comment]
Yup, that is not the behavior I intended.
@d-rams thank you so much for bringing this to my attention!
